### ISSUE TITLE
[UI]:导航栏 icon

### ISSUE THREAD

**Issue by HenryZhang-ZHY** [zjc17/cook.zhangjc.tech#1]
![image](https://user-images.githubusercontent.com/62298214/166457333-0b1d2026-69ae-4dd6-b6ac-5561e90e9c20.png)
这几个 icon 加上 hover 或者 Tooltip 的效果比较好。
现在它们和下面这部分的视觉效果一样，让人感觉这几个 icon 是不可点击的。
![image](https://user-images.githubusercontent.com/62298214/166457752-8b47c34b-e04b-4b42-a46e-042dce5cc930.png)

**Comment by zjc17** [comment]
@imentu 感谢建议，我添加一下！
